### ISSUE TITLE
Just wanted...

### ISSUE THREAD

**Issue by anonimno1** [krzysztofsroga/Libre-Home-Android#2] opened 2020-01-15 16:15 UTC
to say hi and thank you!
Just installed your app on my LineageOS 16 phone and it is working :)!
Used Domoticz app until now but got tired of Play Services warning (do not have them on my phone). Great to see you started this app without Google stuff!
How can I support you going forward?

**Comment by krzysztofsroga** [comment] 2020-01-17 18:27
Hi! Thank you for the feedback!
I started the project mainly for myself and my family - we needed a fast, lightweight app(opposite to domoticz web client) just to control the switches and restart the raspberry over ssh if something goes wrong with raspberry.
I'm pleasantly surprised that someone is using the app just two weeks after I released first working builds.

When it comes to my plans with the app in the future, I think now the most important things are:
 - releasing app to F-Droid
 - supporting domoticz user accounts
 - supporting https connection (but for this to be tested, I need to configure my domoticz to support this)
I'm also going to replace fuel with retrofit or at least check how does it fit into the app because I want to learn how to use the library.

I have a Trello board with some to-do list: https://trello.com/b/34yjlYgO/librehome
I will add it to readme file as soon as I clean it up a little bit. 
If you feel like it, feel free to create pull requests with those solved.

**If you have your own ideas about the app(functionality, UI changes, some graphics) - please, share them, I will be happy to see your point of view.** 

But until the end of February I'm pretty busy writing my BS thesis so until then the project may stagnate a little bit.

**Comment by anonimno1** [comment] 2020-01-22 17:27
Hi,

yes, I am also looking for lightweight Domoticz app and yours came up :)!
Your ideas are great but please keep the Ok, Google out of it. F-Droid also doesn't want to see it, so just keep it FOSS :).
It would be great to have different pages in the app for switches/scenes/sensors. Then we can add to favs to have a dashboard.

Give me a ping, when you want something tested! i have https at home.

Regards
Kemal

Am 17. Januar 2020 19:27:39 MEZ schrieb Krzysztof Sroga <notifications@github.com>:

**Comment by anonimno1** [comment] 2020-01-29 09:30
Hi again,

I just had a little bit more time to use the app.
A couple of tipps:

1. I have a lot of different arts of devices in Domoticz (switches, push on buttons, multiselector switches etc.). Right now all this different devices are shown as simple switches. It would be great to at least be able to have multiselector switches and push on buttons.
2. For the SSH you only have a field for password. Which username is used? Is it possible to implement the ssh with the private/public key? This is how I have it :). 
3. I have different Raspis doing different stuff in the house. It would be a great thing to also have a possibility to add different ssh hosts for the reset command.

Regards
Kemal

**Comment by krzysztofsroga** [comment] 2020-01-29 23:42
Thank you!
1. Yeah, this one is definitely on the todo list!
2. Default username 'pi' is used for now. I'll add possibility to change it.
3. Okay, I can see how this can be useful. For me it's low priority but it'll be added some time in the future.

Thanks for the suggestions, I'll note them down. And as I said, I'll be back in a project after the end of February.

**Comment by krzysztofsroga** [comment] 2020-02-23 15:32
@anonimno1 
I added your German translation to the next release. I also allowed changing the ssh username, implemented sorting and Selector Switch. That last one took a little bit tinkering to have it the same way as on web version but it looks like it's finally working well. Check it out and let me know :) 
https://github.com/krzysztofsroga/Libre-Home-Android/releases/tag/0.3-beta

**Comment by anonimno1** [comment] 2020-02-23 16:29
Hi,

tried it right away but I get "Connection error:throw with null exception". No connection to domoticz!
Also German is used right away, although in menu English is default. You changed it, that locale is read out and used?

Regards
K

Am 23. Februar 2020 16:32:17 MEZ schrieb Krzysztof Sroga <notifications@github.com>:

**Comment by krzysztofsroga** [comment] 2020-02-23 16:54
Hmm, ok, I was able to reproduce it. Weird, but it happens only in release build... I'll fix it tomorrow.

**Comment by krzysztofsroga** [comment] 2020-02-24 00:46
Okay, I re-uploaded the apk file with fixed proguard rules.

**Comment by anonimno1** [comment] 2020-02-24 06:01
Not working, I get another error now.
See attachment.

Am 24. Februar 2020 01:46:45 MEZ schrieb Krzysztof Sroga <notifications@github.com>:

**Comment by krzysztofsroga** [comment] 2020-02-24 08:48
Sorry, I can't see it. I think, if you want to attach files, you need to do it via web GitHub client, not by email.

**Comment by anonimno1** [comment] 2020-02-24 08:58
"Attempt to invoke a virtual method "int java.lang.string.hashcode()" on a null object reference"

Hope this helps :)

Am 24. Februar 2020 09:48:54 MEZ schrieb Krzysztof Sroga <notifications@github.com>:

**Comment by krzysztofsroga** [comment] 2020-02-24 14:41
It's too little information for me to fix that. I can't reproduce this error so I need at least a stacktrace. 
I uploaded a new release (0.3.2) which features logging. Recent logs can be accessed from the top menu in statusbar.
Just send me the log here or to support@sroga.dev 
I hope I would be able to figure something out of it. If not, I would need to try it on my phone with your example response from http://domoticz:8080/json.htm?type=devices&filter=lights&used=true&order=Name

**Comment by anonimno1** [comment] 2020-02-25 15:45
Hi,

I am on buisness trip right now and will try the new version with logging on weekend.

Regards
k

Am 24. Februar 2020 20:11:46 GMT+05:30 schrieb Krzysztof Sroga <notifications@github.com>:

**Comment by anonimno1** [comment] 2020-03-01 17:37
Hi,
I just sent you the log!

Regards
K

Am 24. Februar 2020 15:41:46 MEZ schrieb Krzysztof Sroga <notifications@github.com>:

**Comment by krzysztofsroga** [comment] 2020-03-02 13:37
Hi,
Thanks. I went through various possibilities and it looks like the only way for this to happen is that one or more of your switches has no `SwitchType` field at all. I didn't think it was possible. I will post a fixed version later today.

**Comment by anonimno1** [comment] 2020-03-02 13:40
I have a lot of virtual switches in my config. Maybe this is the issue?
I also have scenes and sensors defined. This should not interfere with Switches?

Am 2. März 2020 14:37:08 MEZ schrieb Krzysztof Sroga <notifications@github.com>:

**Comment by anonimno1** [comment] 2020-03-02 13:44
I just saw in my Librehome under switches and everything that is virtual (switches, sensors ..) is there!
So I would presume, this is making problems.

Am 2. März 2020 14:40:17 MEZ schrieb anonimno@mailbox.org:
>I have a lot of virtual switches in my config. Maybe this is the issue?
>I also have scenes and sensors defined. This should not interfere with
>Switches?
>
>Am 2. März 2020 14:37:08 MEZ schrieb Krzysztof Sroga
><notifications@github.com>:
>>Hi,
>>Thanks. I went through various possibilities and it looks like the
>only
>>way for this to happen is that one or more of your switches has no
>>`SwitchType` field at all. I didn't think it was possible. I will post
>>a fixed version later today.
>>
>>-- 
>>You are receiving this because you were mentioned.
>>Reply to this email directly or view it on GitHub:
>>https://github.com/krzysztofsroga/Libre-Home-Android/issues/2#issuecomment-593405682

-- 
Kemal Hajvazovic
E: kemal@mailbox.org
M: +491628231843

**Comment by krzysztofsroga** [comment] 2020-03-02 13:56
I have scenes and virtual switches too and they work well. Maybe domoticz is returning something else as a switch... I'll just configure it to ignore these without a switch type and it will work fine.

Anyway, for future debugging, if you are okay with sharing your switches data with me, you can go to  http://domoticz:8080/json.htm?type=devices&filter=lights&used=true&order=Name (or equivalent location), save it to a file and send it to my email. The output contains all switch names, types and their possible values. The same data my app is parsing to display them. I would be able to fix future problems more quickly and test the app on your data.

**Comment by anonimno1** [comment] 2020-03-02 14:05
Hi,

I just sent you my switches.
My Scenes are not shown in Librehome. How do I get this?


Am 2. März 2020 14:56:39 MEZ schrieb Krzysztof Sroga <notifications@github.com>:

**Comment by krzysztofsroga** [comment] 2020-03-02 14:10
Hi,
Thanks, I'll look into this and see how the app works with your data. The scenes will also be displayed.

**Comment by anonimno1** [comment] 2020-03-02 16:16
Hi,

sorry to bother you, but maybe take a look at these device types:

1. Roollladen* - these are shades for the windows that are 0-100%.
2. Media - this is a push off button
3. Rockrobo_Staubbähelterleeren_ein - this is a push on button.

Regards
K

Am 2. März 2020 15:10:13 MEZ schrieb Krzysztof Sroga <notifications@github.com>:

**Comment by krzysztofsroga** [comment] 2020-03-04 12:04
I hope everything is fixed in todays release. Domoticz groups and scenes are also supported.

**Comment by anonimno1** [comment] 2020-03-04 12:18
Hi,

I installed it and connection works now!
Will test more and give you feedback later.
Great work!

Am 4. März 2020 13:04:04 MEZ schrieb Krzysztof Sroga <notifications@github.com>:

**Closed as completed** 2020-05-12 05:45 UTC
